<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="VanChan" failures="1" tests="4" name="Guru 99 Smoke Test Demo" time="47.218" errors="0" timestamp="2024-04-08T11:41:17 ICT">
  <testcase classname="com.parabanknew.test.RegisterTest" name="testRegisterSuccess" time="6.708"/>
  <testcase classname="com.parabanknew.test.RegisterTest" name="testRegisterUsernameEmpty" time="6.37"/>
  <testcase classname="com.parabanknew.test.RegisterTest" name="testRegisterPasswordEmpty" time="6.441"/>
  <testcase classname="com.parabanknew.test.RegisterTest" name="testRegisterUsernameExist" time="10.365">
    <failure type="java.lang.AssertionError" message="Wrong message in case username is existed expected [This username already exists....] but found [This username already exists.]">
      <![CDATA[java.lang.AssertionError: Wrong message in case username is existed expected [This username already exists....] but found [This username already exists.]
at com.parabanknew.test.RegisterTest.testRegisterUsernameExist(RegisterTest.java:142)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testRegisterUsernameExist -->
</testsuite> <!-- Guru 99 Smoke Test Demo -->
